---
- hosts: all
  become: true
  name: builder
  tasks:

  - name: Create Ansible Local Facts Directory
    file: path=/etc/ansible/facts.d state=directory

  - name: Initiate Build Numbering
    copy: >
        content='{ "build_counter":"1" }'
        dest="/etc/ansible/facts.d/builder.fact"
        force=no

  - name: Reload Ansible Local Facts
    setup: filter=ansible_local

  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Install devscripts and equivs to extract build dependencies
    apt: name={{item}} state=present
    with_items:
      - devscripts
      - equivs

  - name: Install Apache server for hosting Debian Repository
    apt: name={{item}} state=present
    with_items:
      - apache2

  - name: Clean Open vSwitch GIT repository
    command: chdir=/var/www/html/debs/amd64/ovs/ git clean -xdf

  - name: Reset Open vSwitch GIT repository
    command: chdir=/var/www/html/debs/amd64/ovs/ git reset --hard

  - name: Get Open vSwitch version from debian/changelog
    command: >
            chdir=/var/www/html/debs/amd64/ovs/
            dpkg-parsechangelog --show-field Version
    register: version_number

  - name: Concatenate full version
    set_fact:
        full_version: "{{version_number.stdout}}loc{{ansible_local.builder.build_counter}}"

  - name: Update Open vSwitch version to {{full_version}}
    command: >
            chdir=/var/www/html/debs/amd64/ovs/
            dch -b -v {{full_version}} Vagrant Build

  - name: Build debian package with Open vSwitch build dependencies
    command: >
            chdir=/var/www/html/debs/amd64/ovs/
            mk-build-deps -B debian/control

  - name: Install Open vSwitch {{full_version}} build dependencies
    apt: >
            deb=/var/www/html/debs/amd64/ovs/openvswitch-build-deps-depends_{{full_version}}_all.deb

  - name: Build Open vSwitch {{full_version}} debian packages
    shell: DEB_BUILD_OPTIONS='parallel=8 nocheck' fakeroot debian/rules binary
    args:
       chdir: /var/www/html/debs/amd64/ovs/

  - name: Create apt get directory server by Web Server
    file: path=/var/www/html/debs/amd64 state=directory

  - name: Set up Debian repository with Open vSwitch packages
    shell: dpkg-scanpackages amd64 | gzip -9c > amd64/Packages.gz
    args:
       chdir: /var/www/html/debs

  - name: Bump up Build Number
    copy: >
        content='{ "build_counter":"{{ansible_local.builder.build_counter|int+1}}" }'
        dest="/etc/ansible/facts.d/builder.fact"
