# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "8"]
  end

  # Ubuntu builder host
  config.vm.define "ubuntubuilder" do |builder|
    builder.vm.hostname = "ubuntubuilder.dev"
    builder.vm.box = "bento/ubuntu-16.04"
    builder.vm.synced_folder "../../", "/var/www/html/debs/amd64/ovs", type: "rsync", rsync__args: ["--verbose", "--archive", "--delete", "-z"]
    builder.vm.network :private_network, ip: "192.168.60.10"
    builder.vm.provision "builder", type: "ansible" do |ansible|
      ansible.playbook = "../playbook-builder.yml"
      ansible.sudo = true
    end
  end

  # The host running DPI engine
  config.vm.define "dpi" do |host|
    host.vm.hostname = "dpi.dev"
    host.vm.box = "bento/ubuntu-16.04"
    host.vm.network :private_network, ip: "192.168.60.101"
    host.vm.provision "kernel-debug", type: "ansible" do |ansible|
      ansible.playbook = "../kernel-debug.yml"
      ansible.sudo = true
    end
    host.vm.provision "dpi", type: "ansible" do |ansible|
      ansible.playbook = "../playbook-dpi.yml"
      ansible.sudo = true
    end

  end

end

